### ISSUE TITLE
Repo TODO

### ISSUE THREAD

**Issue by FOREVEREALIZE** [NewWind-Modpacks/Waste-of-World#3]
- [x] Clean up `.bak` files (Addressed by #7)
- [x] Add `.gitignore` (Addressed by #6)
- [x] Make GitHub Action that formats `manifest.json` (Addressed by #8)
- [x] Sync Resource Packs through Git (See #12)
- [x] Fix formatter (Addressed by #9)
